[build]
  publish = "dist"
  command = "pnpm build"
  functions = "netlify/functions"

[dev]
  command = "pnpm dev:vite"
  targetPort = 5173
  port = 8888
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
